# Generated by Django 3.0.5 on 2020-07-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=10)),
                ('imagen', models.ImageField(upload_to='')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
