# Generated by Django 3.0.5 on 2020-07-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0004_auto_20200714_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
